import { cloneProfile } from "../types.mjs";
import { callJsonLlm } from "./llmClient.mjs";

function normalizeQuestion(question = {}, fallbackId = "llm-next-question") {
  if (!question?.prompt) return null;

  return {
    id: question.id || fallbackId,
    prompt: question.prompt,
    reason: question.reason || "",
    layer: question.layer || "background",
    source: "llm-interview",
  };
}

function normalizeSignals(signals = []) {
  return Array.isArray(signals)
    ? signals
        .filter((signal) => signal?.field && signal.value !== undefined && signal.value !== null && signal.value !== "")
        .map((signal) => ({
          field: String(signal.field),
          value: signal.value,
          source: "llm-state",
        }))
    : [];
}

export async function generateInterviewStateWithLlm({
  profile,
  askedQuestionIds = [],
  transcript = [],
  latestAnswer = "",
  latestQuestionId = "",
  airjelly = {},
  options = {},
}) {
  if (!options.enabled) return null;

  const result = await callJsonLlm({
    options: options.llm || {},
    temperature: 0.2,
    system: [
      "You are the deep interview engine for a career planning product.",
      "Do not use a fixed question bank. Decide the next highest-information question from the user's real profile, transcript, and memory context.",
      "You also decide profile completeness, missing areas, and whether the product should keep interviewing or move to planning.",
      "AirJelly taskQueue.byScene contains open tasks grouped by l1_scene; treat each scene as the queue for its specialized agent and read task progress, next plan, and memories before making judgments.",
      "Ask exactly one concise Chinese question unless the profile is ready for planning.",
      "Return user-facing text only if it was generated by you. Do not copy template questions or internal labels.",
    ].join(" "),
    schemaHint:
      '{"completeness":0,"shouldAdviseNow":false,"phase":"interviewing|ready_for_planning","nextQuestion":{"id":"string","prompt":"string","reason":"string","layer":"background|conflict|value-ranking|done"},"extractedSignals":[{"field":"string","value":"string|number|boolean|object"}],"interviewBoard":{"currentLayer":"string","interviewerMode":"string","missingChecklist":[{"key":"string","done":false,"prompt":"string"}],"firstTurnAgenda":["string"],"proactiveQuestions":[{"id":"string","prompt":"string","layer":"string","reason":"string"}],"suggestedNextQuestion":{"id":"string","prompt":"string","layer":"string","reason":"string"}}}',
    user: JSON.stringify({
      currentProfile: profile,
      askedQuestionIds,
      latestTurn: latestQuestionId
        ? {
            questionId: latestQuestionId,
            answer: latestAnswer,
          }
        : null,
      recentTranscript: transcript.slice(-8),
      airjellySummary: airjelly.contextSummary || null,
      airjellyTaskQueue: airjelly.taskQueue || null,
      airjellyHints: {
        counterEvidence: airjelly.counterEvidence || [],
        interviewHints: airjelly.interviewHints || [],
      },
    }),
  });

  if (!result.available || !result.data) return null;

  const nextQuestion = normalizeQuestion(result.data.nextQuestion);
  const interviewBoard = {
    ...(result.data.interviewBoard || {}),
    completeness: Math.max(0, Math.min(100, Number(result.data.completeness || 0))),
    suggestedNextQuestion:
      normalizeQuestion(result.data.interviewBoard?.suggestedNextQuestion, nextQuestion?.id) || nextQuestion,
    memoryGrounding: {
      available: Boolean(airjelly.available),
      source: airjelly.source || "none",
      dominantMode: airjelly.contextSummary?.dominantMode || "unknown",
      topTasks: airjelly.contextSummary?.topTasks || [],
      focusProjects: airjelly.contextSummary?.focusProjects || [],
      semanticQueries: airjelly.semanticQueries || [],
      semanticSearchEnabled: airjelly.semanticSearchEnabled || false,
      taskQueue: airjelly.taskQueue || null,
    },
  };

  return {
    completeness: interviewBoard.completeness,
    shouldAdviseNow: Boolean(result.data.shouldAdviseNow),
    phase: result.data.phase || "interviewing",
    nextQuestion,
    extractedSignals: normalizeSignals(result.data.extractedSignals),
    interviewBoard,
    llmModel: result.model,
  };
}

export async function generateProfileUpdateWithLlm({
  knownProfile,
  extractedSignals = [],
  rawEvents = [],
  githubSync = {},
  airjelly = {},
  transcript = [],
  options = {},
}) {
  if (!options.enabled) return null;

  const result = await callJsonLlm({
    options: options.llm || {},
    temperature: 0.1,
    system: [
      "You are the canonical profile state manager for a career planning product.",
      "Merge the current profile, latest extracted signals, GitHub evidence, AirJelly evidence, and transcript into one stable full profile.",
      "Use the exact profile schema from the input. Preserve existing stable facts unless the latest evidence clearly updates them.",
      "Do not invent schools, projects, internships, papers, goals, or constraints. Leave unknown information empty or unknown.",
      "You are responsible for profile completeness, contradictions, profile summary, and resume snapshot.",
      "AirJelly taskQueue.byScene contains open tasks grouped by l1_scene for specialized agents. Use each task's progressSummary, nextPlan, and memories as work context.",
      "Return concise Chinese for user-facing summaries.",
    ].join(" "),
    schemaHint:
      '{"profile":{...fullProfileSchema},"completeness":0,"contradictions":["string"],"profileSummary":["string"],"resumeSnapshot":{"headline":"string","education":["string"],"highlights":["string"],"projects":[{"name":"string","type":"string","techStack":["string"],"narrative":"string","technicalDepth":"string","resumeBullets":["string"]}],"experiences":[{"type":"string","name":"string","summary":"string"}],"constraints":["string"],"nextEvidenceToCollect":["string"]}}',
    user: JSON.stringify({
      currentProfile: knownProfile,
      extractedSignals,
      rawEvents,
      githubProfile: githubSync.profile || null,
      githubRepos: (githubSync.repos || []).slice(0, 6).map((repo) => ({
        repo: repo.repo,
        projectType: repo.projectType,
        techStack: repo.techStack,
        activityLevel: repo.activityLevel,
        projectAnalysis: repo.projectAnalysis,
      })),
      airjellyTaskQueue: airjelly.taskQueue || null,
      airjellySignals: airjelly.signals || [],
      airjellyRawEvents: airjelly.rawEvents || [],
      airjellyCounterEvidence: airjelly.counterEvidence || [],
      recentTranscript: transcript.slice(-8),
    }),
  });

  if (!result.available || !result.data?.profile) return null;

  const profile = cloneProfile(result.data.profile);
  const completeness = Math.max(0, Math.min(100, Number(result.data.completeness || 0)));

  return {
    profile,
    completeness,
    contradictions: Array.isArray(result.data.contradictions) ? result.data.contradictions : [],
    profileSummary: Array.isArray(result.data.profileSummary) ? result.data.profileSummary : [],
    resumeSnapshot: result.data.resumeSnapshot || profile.resumeSnapshot,
    llmModel: result.model,
  };
}
