import { completenessOfProfile } from "../types.mjs";

function memoryGrounding(airjellyContext = {}) {
  return {
    available: Boolean(airjellyContext.available),
    source: airjellyContext.source || "none",
    dominantMode: airjellyContext.contextSummary?.dominantMode || "unknown",
    topTasks: airjellyContext.contextSummary?.topTasks || [],
    focusProjects: airjellyContext.contextSummary?.focusProjects || [],
    semanticQueries: airjellyContext.semanticQueries || [],
    semanticSearchEnabled: airjellyContext.semanticSearchEnabled || false,
  };
}

export class DeepInterviewSkill {
  constructor() {
    this.systemPrompt = [
      "DeepInterviewSkill is now a non-generative fallback shell.",
      "User-facing interview questions, interview board content, completeness, and profile signals should be generated by ChatGPT API through profileStateSupport.mjs.",
      "This class only returns neutral placeholders when the API is unavailable.",
    ].join(" ");
  }

  getPromptContract() {
    return {
      systemPrompt: this.systemPrompt,
      outputFormat: {
        nextQuestion: "Generated by ChatGPT API",
        reason: "Generated by ChatGPT API",
        layer: "Generated by ChatGPT API",
        extractedSignals: "Generated by ChatGPT API",
        interviewBoard: "Generated by ChatGPT API",
      },
    };
  }

  planNextQuestion() {
    return {
      id: "llm-required-interview",
      layer: "background",
      prompt: "ChatGPT API 尚未返回下一轮问题。请检查 LLM Key 或稍后重试。",
      reason: "访谈内容已切换为 API 生成，不再使用本地问题库。",
      source: "llm-required",
    };
  }

  buildContradictionQuestion() {
    return {
      id: "llm-required-contradiction",
      layer: "conflict",
      prompt: "ChatGPT API 尚未返回冲突追问。请检查 LLM Key 或稍后重试。",
      reason: "冲突追问已切换为 API 生成，不再使用本地模板。",
      source: "llm-required",
    };
  }

  extractSignals() {
    return [];
  }

  buildInterviewBoard(profile, askedQuestionIds = [], contradictions = [], airjellyContext = {}) {
    const fallbackQuestion = this.planNextQuestion();

    return {
      completeness: completenessOfProfile(profile),
      currentLayer: "api-required",
      interviewerMode: "等待 ChatGPT API 生成访谈状态",
      layerProgress: {},
      missingChecklist: [],
      pendingThemes: [],
      firstTurnAgenda: [],
      suggestedNextQuestion: fallbackQuestion,
      memoryGrounding: memoryGrounding(airjellyContext),
      airjellyBackedQuestions: [],
      proactiveQuestions: [fallbackQuestion],
      contradictionQuestion: contradictions.length ? this.buildContradictionQuestion(contradictions) : null,
      askedQuestionIds,
    };
  }

  evaluate(profile, askedQuestionIds = [], airjellyContext = {}) {
    return {
      completeness: completenessOfProfile(profile),
      nextQuestion: this.planNextQuestion(),
      extractedSignals: [],
      interviewBoard: this.buildInterviewBoard(profile, askedQuestionIds, [], airjellyContext),
      shouldAdviseNow: false,
    };
  }
}
